"""Build a self-contained Python bundle of mtg_outcome_sim for Pyodide.

Reads the source tree, inlines the YAML tag definitions, strips imports
that Pyodide cannot satisfy (pydantic, httpx, typer, rich, scipy), and
writes a single sim_bundle.py file that can be loaded by Pyodide.
"""

import os
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SRC_ROOT = REPO_ROOT / "src" / "mtg_outcome_sim"
OUTPUT = Path(__file__).resolve().parent / "sim_bundle.py"


PYDANTIC_SHIM = '''
# Minimal pydantic shim (pure Python, no dependencies)
class _ValidationError(Exception):
    pass

class _FieldInfo:
    def __init__(self, default=None):
        self.default = default

class _ModelMeta(type):
    pass

class BaseModel(metaclass=_ModelMeta):
    def __init__(self, **data):
        for field_name in list(data.keys()):
            setattr(self, field_name, data[field_name])

    def model_dump(self):
        result = {}
        for key in dir(self):
            if key.startswith("_"):
                continue
            val = getattr(self, key)
            if callable(val):
                continue
            result[key] = val
        return result

    @classmethod
    def model_fields(cls):
        return {}

def field_validator(field_name):
    """No-op decorator for compatibility."""
    def decorator(func):
        return func
    return decorator
'''


def read_file(path: Path) -> str:
    with open(path, encoding="utf-8") as f:
        return f.read()


def transform_source(source: str, rel_path: str) -> str:
    """Transform a source file for inclusion in the bundle.

    - Convert relative imports to absolute
    - Remove pydantic, yaml, scipy, pathlib imports (we provide shims)
    - Strip docstring (redundant)
    """
    # Relative imports -> absolute (handling various forms)
    replacements = [
        ("from .plain_text import", "from mtg_outcome_sim.decklist.plain_text import"),
        ("from .parser import", "from mtg_outcome_sim.decklist.parser import"),
        ("from .schema import", "from mtg_outcome_sim.tags.schema import"),
        ("from .classifier import", "from mtg_outcome_sim.tags.classifier import"),
        ("from .hypergeometric import", "from mtg_outcome_sim.simulation.hypergeometric import"),
        ("from .monte_carlo import", "from mtg_outcome_sim.simulation.monte_carlo import"),
        ("from .outcome import", "from mtg_outcome_sim.simulation.outcome import"),
        ("from .simulation", "from mtg_outcome_sim.simulation"),
        ("from .cards", "from mtg_outcome_sim.cards"),
        ("from .tags", "from mtg_outcome_sim.tags"),
        ("from .decklist", "from mtg_outcome_sim.decklist"),
        ("from .reports", "from mtg_outcome_sim.reports"),
    ]
    for old, new in replacements:
        source = source.replace(old, new)

    # Remove import lines that we replace with shims
    remove_lines = [
        "from pydantic import BaseModel, field_validator\n",
        "from pydantic import BaseModel\n",
        "import yaml\n",
        "from pathlib import Path\n",
    ]
    for line in remove_lines:
        source = source.replace(line, "")

    # For hypergeometric.py: replace the entire scipy try/except block
    # with a simple flag that forces the pure-Python path.
    import re
    source = re.sub(
        r"_SCIPY_AVAILABLE = False\ntry:\n    from scipy\.stats import hypergeom[^\n]*\n    _SCIPY_AVAILABLE = True\nexcept ImportError:\n    pass",
        "_SCIPY_AVAILABLE = False  # always use pure-Python in Pyodide",
        source,
    )

    # Strip leading docstring
    stripped = source.strip()
    if stripped.startswith('"""') or stripped.startswith('r"""'):
        idx = stripped.index('"""', 3)
        source = stripped[idx + 3:].strip()
    elif stripped.startswith("'''"):
        idx = stripped.index("'''", 3)
        source = stripped[idx + 3:].strip()

    return source


def build_bundle() -> str:
    """Return the complete bundle source as a string."""

    # Read default_tags.yaml content and escape for embedding
    tags_yaml_path = SRC_ROOT / "tags" / "default_tags.yaml"
    tags_yaml_content = read_file(tags_yaml_path)

    parts = []

    # Header
    parts.append('"""Self-contained mtg_outcome_sim bundle for Pyodide.')
    parts.append("")
    parts.append("Auto-generated by build_bundle.py. Do not edit by hand.")
    parts.append('"""')
    parts.append("")

    # ---- Pydantic shim ----
    parts.append("# ---- Pydantic shim ----")
    parts.append(PYDANTIC_SHIM.strip())
    parts.append("")

    # ---- Import yaml (Pyodide provides pyyaml package) ----
    parts.append("# ---- yaml (provided by Pyodide pyyaml package) ----")
    parts.append("import yaml")
    parts.append("")

    # ---- Path shim ----
    parts.append("# ---- Path (stdlib, available) ----")
    parts.append("from pathlib import Path")
    parts.append("")

    # ---- Module: plain_text ----
    parts.append("# ---- mtg_outcome_sim.decklist.plain_text ----")
    src = read_file(SRC_ROOT / "decklist" / "plain_text.py")
    parts.append(transform_source(src, "decklist/plain_text.py"))
    parts.append("")

    # ---- Module: parser ----
    parts.append("# ---- mtg_outcome_sim.decklist.parser ----")
    src = read_file(SRC_ROOT / "decklist" / "parser.py")
    parts.append(transform_source(src, "decklist/parser.py"))
    parts.append("")

    # ---- Module: schema ----
    parts.append("# ---- mtg_outcome_sim.tags.schema ----")
    src = read_file(SRC_ROOT / "tags" / "schema.py")
    parts.append(transform_source(src, "tags/schema.py"))
    parts.append("")

    # ---- Module: classifier ----
    parts.append("# ---- mtg_outcome_sim.tags.classifier ----")
    src = read_file(SRC_ROOT / "tags" / "classifier.py")
    # We need to replace the file-based YAML loading with inline content
    # The _load_tags function reads from Path(__file__).parent / "default_tags.yaml"
    # We'll replace that with a string-based load
    src = src.replace(
        'yaml_path = Path(__file__).parent / "default_tags.yaml"',
        'yaml_path = None  # replaced by inline content below'
    )
    # Escape backslashes in YAML content to avoid Python SyntaxWarning
    escaped_yaml = tags_yaml_content.replace("\\", "\\\\")
    src = src.replace(
        'data = yaml.safe_load(yaml_path.read_text())',
        f'data = yaml.safe_load("""{escaped_yaml}""")'
    )
    parts.append(transform_source(src, "tags/classifier.py"))
    parts.append("")

    # ---- Module: hypergeometric ----
    parts.append("# ---- mtg_outcome_sim.simulation.hypergeometric ----")
    src = read_file(SRC_ROOT / "simulation" / "hypergeometric.py")
    parts.append(transform_source(src, "simulation/hypergeometric.py"))
    parts.append("")

    # ---- Module: outcome ----
    parts.append("# ---- mtg_outcome_sim.simulation.outcome ----")
    src = read_file(SRC_ROOT / "simulation" / "outcome.py")
    parts.append(transform_source(src, "simulation/outcome.py"))
    parts.append("")

    # ---- Module: monte_carlo ----
    parts.append("# ---- mtg_outcome_sim.simulation.monte_carlo ----")
    src = read_file(SRC_ROOT / "simulation" / "monte_carlo.py")
    parts.append(transform_source(src, "simulation/monte_carlo.py"))
    parts.append("")

    # ---- Namespace glue ----
    parts.append("# ---- Namespace setup ----")
    # We need to ensure all imports resolve. The key issue is that Python
    # source in this file defines mtg_outcome_sim.* modules, but they
    # aren't in sys.modules. We use a workaround: define package proxies
    # and register them in sys.modules.
    parts.append("""
import sys as _sys

class _Module:
    pass

# Create the package hierarchy
_mtg = _Module()
_mtg.decklist = _Module()
_mtg.decklist.plain_text = _Module()
_mtg.decklist.parser = _Module()
_mtg.tags = _Module()
_mtg.tags.schema = _Module()
_mtg.tags.classifier = _Module()
_mtg.simulation = _Module()
_mtg.simulation.hypergeometric = _Module()
_mtg.simulation.outcome = _Module()
_mtg.simulation.monte_carlo = _Module()

# Register in sys.modules
_sys.modules["mtg_outcome_sim"] = _mtg
_sys.modules["mtg_outcome_sim.decklist"] = _mtg.decklist
_sys.modules["mtg_outcome_sim.decklist.plain_text"] = _mtg.decklist.plain_text
_sys.modules["mtg_outcome_sim.decklist.parser"] = _mtg.decklist.parser
_sys.modules["mtg_outcome_sim.tags"] = _mtg.tags
_sys.modules["mtg_outcome_sim.tags.schema"] = _mtg.tags.schema
_sys.modules["mtg_outcome_sim.tags.classifier"] = _mtg.tags.classifier
_sys.modules["mtg_outcome_sim.simulation"] = _mtg.simulation
_sys.modules["mtg_outcome_sim.simulation.hypergeometric"] = _mtg.simulation.hypergeometric
_sys.modules["mtg_outcome_sim.simulation.outcome"] = _mtg.simulation.outcome
_sys.modules["mtg_outcome_sim.simulation.monte_carlo"] = _mtg.simulation.monte_carlo

# Export public symbols to their module namespaces
_mtg.decklist.plain_text.parse_plain_text = parse_plain_text
_mtg.decklist.parser.ParsedCard = ParsedCard
_mtg.decklist.parser.ParsedDeck = ParsedDeck
_mtg.decklist.parser.parse_decklist = parse_decklist
_mtg.tags.schema.TagDefinition = TagDefinition
_mtg.tags.schema.CardTags = CardTags
_mtg.tags.schema.TagOverrides = TagOverrides
_mtg.tags.classifier.classify_card = classify_card
_mtg.tags.classifier.classify_cards = classify_cards
_mtg.simulation.hypergeometric.prob_at_least = prob_at_least
_mtg.simulation.hypergeometric.prob_exact = prob_exact
_mtg.simulation.hypergeometric.opening_hand_distribution = opening_hand_distribution
_mtg.simulation.hypergeometric.lands_by_turn = lands_by_turn
_mtg.simulation.outcome.OutcomeDefinition = OutcomeDefinition
_mtg.simulation.outcome.OutcomeConfig = OutcomeConfig
_mtg.simulation.outcome.load_outcomes = load_outcomes
_mtg.simulation.monte_carlo.MCResult = MCResult
_mtg.simulation.monte_carlo.run_simulation = run_simulation
_mtg.simulation.monte_carlo.run_all_outcomes = run_all_outcomes
""")

    return "\n".join(parts)


def main():
    bundle = build_bundle()
    OUTPUT.write_text(bundle, encoding="utf-8")
    print(f"Bundle written to {OUTPUT}")
    print(f"  {len(bundle):,} characters, {bundle.count(chr(10)):,} lines")


if __name__ == "__main__":
    main()
