"""Self-contained mtg_outcome_sim bundle for Pyodide.

Auto-generated by build_bundle.py. Do not edit by hand.
"""

# ---- Pydantic shim ----
# Minimal pydantic shim (pure Python, no dependencies)
class _ValidationError(Exception):
    pass

class _FieldInfo:
    def __init__(self, default=None):
        self.default = default

class _ModelMeta(type):
    pass

class BaseModel(metaclass=_ModelMeta):
    def __init__(self, **data):
        for field_name in list(data.keys()):
            setattr(self, field_name, data[field_name])

    def model_dump(self):
        result = {}
        for key in dir(self):
            if key.startswith("_"):
                continue
            val = getattr(self, key)
            if callable(val):
                continue
            result[key] = val
        return result

    @classmethod
    def model_fields(cls):
        return {}

def field_validator(field_name):
    """No-op decorator for compatibility."""
    def decorator(func):
        return func
    return decorator

# ---- yaml (provided by Pyodide pyyaml package) ----
import yaml

# ---- Path (stdlib, available) ----
from pathlib import Path

# ---- mtg_outcome_sim.decklist.plain_text ----
import re

def parse_plain_text(text: str) -> list[tuple[int, str]]:
    """Parse a plain-text decklist into (quantity, card_name) tuples."""
    cards = []
    for line in text.strip().split("\n"):
        line = line.strip()
        if not line or line.startswith("#") or line.startswith("//"):
            continue
        # Remove set codes, collector numbers, foil markers
        line = re.sub(r'\s*\([^)]*\)\s*', ' ', line)
        line = re.sub(r'\s*\*F\*\s*', ' ', line)
        # Match "1 Card Name" or "1x Card Name"
        m = re.match(r'^(\d+)\s*x?\s*(.+?)\s*$', line, re.IGNORECASE)
        if m:
            qty = int(m.group(1))
            name = m.group(2).strip()
            cards.append((qty, name))
    return cards


# ---- mtg_outcome_sim.decklist.parser ----
from mtg_outcome_sim.decklist.plain_text import parse_plain_text

class ParsedCard(BaseModel):
    name: str
    quantity: int

class ParsedDeck(BaseModel):
    cards: list[ParsedCard]
    total_count: int
    format: str = "unknown"

def parse_decklist(text: str) -> ParsedDeck:
    """Parse a decklist string into a ParsedDeck."""
    raw = parse_plain_text(text)
    cards = [ParsedCard(name=name, quantity=qty) for qty, name in raw]
    total = sum(c.quantity for c in cards)
    # Detect commander: ~100 cards, singleton (all qty=1 for non-basics, basics can be many)
    fmt = "commander" if 98 <= total <= 100 else "unknown"
    return ParsedDeck(cards=cards, total_count=total, format=fmt)


# ---- mtg_outcome_sim.tags.schema ----

class TagDefinition(BaseModel):
    name: str
    description: str
    oracle_patterns: list[str] = []
    type_line_patterns: list[str] = []
    exclude_if_tags: list[str] = []

class CardTags(BaseModel):
    card_name: str
    tags: set[str] = set()

class TagOverrides(BaseModel):
    card_name: str
    tags: set[str] = set()


# ---- mtg_outcome_sim.tags.classifier ----
import re
from mtg_outcome_sim.tags.schema import TagDefinition, CardTags, TagOverrides

_TAGS: list[TagDefinition] | None = None

# Ramp-effect patterns that justify the ramp tag even on lands (fetchlands, etc.).
# These match land-searching and land-putting effects, NOT basic mana abilities.
# Since these are only checked for cards already tagged as "lands", we can use
# broader patterns that catch named land types (Forest, Swamp, etc.).
_LAND_RAMP_PATTERNS = [
    re.compile(r"(?i)search your library for (?:a |an |basic )"),  # fetchland / land tutor
    re.compile(r"(?i)put (?:it|them|that) onto the battlefield"),  # put fetched land into play
]


def _load_tags() -> list[TagDefinition]:
    global _TAGS
    if _TAGS is not None:
        return _TAGS
    yaml_path = None  # replaced by inline content below
    data = yaml.safe_load("""tags:
  - name: lands
    description: "Cards that produce mana from the land slot"
    oracle_patterns: []
    type_line_patterns:
      - '(?i)land'
  - name: ramp
    description: "Cards that accelerate mana beyond one land per turn"
    oracle_patterns:
      - '(?i)search your library for a.*land'
      - '(?i)add \\{.*\\}'
      - '(?i)put.*land.*onto the battlefield'
      - '(?i)add .* mana'
      - '(?i)untap target.*land'
    type_line_patterns: []
    exclude_if_tags: ["lands"]
  - name: draw
    description: "Cards that draw additional cards"
    oracle_patterns:
      - '(?i)draw.*cards?'
      - '(?i)draw a card'
    type_line_patterns: []
  - name: removal
    description: "Cards that remove threats from the battlefield"
    oracle_patterns:
      - '(?i)destroy target'
      - '(?i)exile target'
      - '(?i)deal.*damage to.*target'
      - '(?i)-\\d+/-\\d+.*target'
      - '(?i)fights? target'
      - '(?i)target.*gets? -\\d+'
    type_line_patterns: []
  - name: combo_piece
    description: "Part of a game-winning combo (requires manual tagging)"
    oracle_patterns: []
    type_line_patterns: []
  - name: payoff
    description: "Cards that reward the deck's primary strategy"
    oracle_patterns:
      - '(?i)whenever.*dies'
      - '(?i)whenever.*enter.*graveyard'
      - '(?i)whenever.*leaves the battlefield'
      - '(?i)whenever.*you sacrifice'
      - '(?i)each opponent loses.*life'
      - '(?i)whenever.*creature.*dies'
      - '(?i)drain'
    type_line_patterns: []
  - name: sac_outlet
    description: "Cards that let you sacrifice creatures at will"
    oracle_patterns:
      - '(?i)sacrifice a creature'
      - '(?i)sacrifice another creature'
      - '(?i)sacrifice.*creature.*:'
    type_line_patterns: []
  - name: token_maker
    description: "Cards that create creature tokens"
    oracle_patterns:
      - '(?i)create.*token'
      - '(?i)create a.*creature token'
    type_line_patterns: []
  - name: engine_piece
    description: "Cards that generate incremental value over time"
    oracle_patterns:
      - '(?i)whenever you draw'
      - '(?i)whenever you cast'
      - '(?i)at the beginning of.*upkeep'
      - '(?i)whenever.*enter.*under your control'
      - '(?i)whenever.*attack'
    type_line_patterns: []
""")
    _TAGS = [TagDefinition(**t) for t in data["tags"]]
    return _TAGS


def classify_card(
    name: str,
    oracle_text: str,
    type_line: str,
    overrides: dict[str, set[str]] | None = None,
) -> CardTags:
    """Classify a single card, returning its functional tags. Cards can have multiple tags."""
    tags: set[str] = set()
    for td in _load_tags():
        for pat in td.type_line_patterns:
            if re.search(pat, type_line):
                tags.add(td.name)
                break
        for pat in td.oracle_patterns:
            if re.search(pat, oracle_text):
                tags.add(td.name)
                break

    # Apply exclude_if_tags: remove a tag if the card already has one of the excluded tags.
    # Example: ramp exclude_if_tags ["lands"] removes ramp from basic lands that
    # matched via the "add {.*}" mana-ability pattern.
    for td in _load_tags():
        if td.exclude_if_tags and td.name in tags:
            if any(excluded in tags for excluded in td.exclude_if_tags):
                tags.discard(td.name)

    # Re-add ramp for lands that have true ramp effects (fetchlands, land-putting spells).
    if "lands" in tags and "ramp" not in tags:
        for pat in _LAND_RAMP_PATTERNS:
            if pat.search(oracle_text):
                tags.add("ramp")
                break

    if overrides and name in overrides:
        tags = tags | overrides[name]
    return CardTags(card_name=name, tags=tags)

def classify_cards(cards: list[tuple[str, str, str]], overrides: dict[str, set[str]] | None = None) -> list[CardTags]:
    """Classify multiple cards. cards = list of (name, oracle_text, type_line)."""
    return [classify_card(n, o, t, overrides) for n, o, t in cards]


# ---- mtg_outcome_sim.simulation.hypergeometric ----
import math


# ---------------------------------------------------------------------------
# Pure-Python hypergeometric primitives (no scipy required)
# ---------------------------------------------------------------------------

def _hypergeom_pmf(k: int, N: int, K: int, n: int) -> float:
    """Hypergeometric PMF: P(X = k). Pure Python using math.comb."""
    if k < 0 or k > K or k > n or n - k > N - K:
        return 0.0
    return (math.comb(K, k) * math.comb(N - K, n - k)) / math.comb(N, n)


def _hypergeom_sf(k: int, N: int, K: int, n: int) -> float:
    """Hypergeometric survival function: P(X > k) = 1 - P(X <= k)."""
    total = 0.0
    for i in range(k + 1):
        total += _hypergeom_pmf(i, N, K, n)
    return 1.0 - total


def _hypergeom_pmf_scalar(k: int, N: int, K: int, n: int) -> float:
    """Hypergeometric PMF: P(X = k). Pure Python using math.comb.

    (Backward-compatible alias kept for internal use.)
    """
    return _hypergeom_pmf(k, N, K, n)


# ---------------------------------------------------------------------------
# Public API – try scipy first, fall back to pure Python
# ---------------------------------------------------------------------------

_SCIPY_AVAILABLE = False  # always use pure-Python in Pyodide


def prob_at_least(
    population: int, successes: int, draws: int, minimum: int
) -> float:
    """Probability of drawing at least `minimum` success cards in `draws` draws.

    P(X >= minimum) = sf(minimum - 1) where sf is the survival function.

    Args:
        population: Total cards in deck (e.g. 99 for Commander).
        successes: Number of cards in deck that have the target tag.
        draws: Number of cards drawn (opening 7 + natural draws + extra).
        minimum: Minimum number of success cards wanted.

    Returns:
        Probability in [0.0, 1.0].

    Edge cases:
        minimum <= 0  -> 1.0 (zero or fewer is always satisfied)
        minimum > draws  -> 0.0 (cannot draw more than drawn)
        minimum > successes -> 0.0 (not enough in deck)
        draws > population -> draws clamped to population
    """
    if minimum <= 0:
        return 1.0
    if minimum > draws or minimum > successes:
        return 0.0
    if draws > population:
        draws = population

    if _SCIPY_AVAILABLE:
        # P(X >= minimum) = sf(minimum - 1)
        return float(hypergeom.sf(minimum - 1, population, successes, draws))
    else:
        return _hypergeom_sf(minimum - 1, population, successes, draws)


def prob_exact(
    population: int, successes: int, draws: int, count: int
) -> float:
    """Probability of drawing exactly `count` success cards.

    Args:
        population: Total cards in deck.
        successes: Number of cards in deck that have the target tag.
        draws: Number of cards drawn.
        count: Exact number of success cards wanted.

    Returns:
        Probability in [0.0, 1.0].
    """
    if count < 0:
        return 0.0
    if count > draws or count > successes or count > population:
        return 0.0
    if draws > population:
        draws = population

    if _SCIPY_AVAILABLE:
        return float(hypergeom.pmf(count, population, successes, draws))
    else:
        return _hypergeom_pmf(count, population, successes, draws)


def opening_hand_distribution(
    deck_size: int, land_count: int, draw_size: int = 7
) -> dict[int, float]:
    """Probability distribution for number of lands in an opening hand.

    Args:
        deck_size: Total cards in deck.
        land_count: Number of lands in the deck.
        draw_size: Cards drawn for opening hand (default 7).

    Returns:
        Dict mapping land_count -> probability.
    """
    dist = {}
    for k in range(draw_size + 1):
        p = prob_exact(deck_size, land_count, draw_size, k)
        if p > 0:
            dist[k] = p
    return dist


def lands_by_turn(
    deck_size: int, land_count: int, turn: int, on_draw: bool = False
) -> list[tuple[int, float]]:
    """Probability distribution of land counts by turn T.

    Draws = 7 (opening) + (turn - 1) natural draws (+ 1 if on the draw).

    Args:
        deck_size: Total cards in deck.
        land_count: Number of lands in the deck.
        turn: Which turn to evaluate (1-indexed).
        on_draw: If True, add one extra card (the player went second).

    Returns:
        List of (land_count, probability) for each possible land count.
    """
    draws = 7 + (turn - 1)
    if on_draw:
        draws += 1
    if draws > deck_size:
        draws = deck_size

    results = []
    for k in range(draws + 1):
        p = prob_exact(deck_size, land_count, draws, k)
        if p > 0:
            results.append((k, p))
    return results

# ---- mtg_outcome_sim.simulation.outcome ----
class OutcomeDefinition(BaseModel):
    """A single outcome question to simulate."""

    name: str
    type: str  # "minimum_cards_seen", "has_tag", "all_groups_present"
    tag: str | None = None
    minimum: int = 1
    by_turn: int
    groups: list[dict] | None = None

    @field_validator("type")
    @classmethod
    def validate_type(cls, v: str) -> str:
        allowed = {"minimum_cards_seen", "has_tag", "all_groups_present"}
        if v not in allowed:
            raise ValueError(
                f"Outcome type must be one of {allowed}, got '{v}'"
            )
        return v

    @field_validator("by_turn")
    @classmethod
    def validate_by_turn(cls, v: int) -> int:
        if v < 1:
            raise ValueError(f"by_turn must be >= 1, got {v}")
        return v

    @field_validator("minimum")
    @classmethod
    def validate_minimum(cls, v: int) -> int:
        if v < 1:
            raise ValueError(f"minimum must be >= 1, got {v}")
        return v


class OutcomeConfig(BaseModel):
    """Top-level configuration for a set of outcome simulations."""

    deck_format: str
    commander: str
    turn_limit: int
    iterations: int
    outcomes: list[OutcomeDefinition]


def load_outcomes(path: Path) -> OutcomeConfig:
    """Load outcome definitions from a YAML file.

    Args:
        path: Path to the YAML file.

    Returns:
        An OutcomeConfig with validated outcome definitions.

    Raises:
        FileNotFoundError: If the file does not exist.
        ValueError: If the YAML is malformed or validation fails.
    """
    data = yaml.safe_load(path.read_text())
    return OutcomeConfig(**data)

# ---- mtg_outcome_sim.simulation.monte_carlo ----
import random
from dataclasses import dataclass
from typing import Any


@dataclass
class MCResult:
    """Result of a single Monte Carlo simulation run."""

    probability: float
    iterations: int
    successes: int


def run_simulation(
    deck_tags: dict[str, set[str]],
    outcome_def: dict[str, Any],
    iterations: int = 100_000,
    seed: int | None = 42,
) -> MCResult:
    """Run Monte Carlo draw simulation for a single outcome question.

    Args:
        deck_tags: Mapping of card_name -> set of tag strings.
        outcome_def: Outcome definition dict with keys:
            - name (str): Human-readable name.
            - type (str): "minimum_cards_seen", "has_tag", or "all_groups_present".
            - tag (str | None): Target tag for single-tag outcomes.
            - minimum (int): Minimum number of tagged cards required.
            - by_turn (int): Turn number by which the condition must be met.
            - groups (list[dict] | None): List of {"tag": str, "minimum": int}
              for all_groups_present outcomes.
        iterations: Number of Monte Carlo trials.
        seed: Random seed for reproducibility (None for non-reproducible).

    Returns:
        MCResult with probability, iteration count, and success count.
    """
    rng = random.Random(seed)

    # Build the deck as a list of (name, tags) tuples.
    deck: list[tuple[str, set[str]]] = list(deck_tags.items())

    outcome_type = outcome_def["type"]
    by_turn = outcome_def["by_turn"]

    # Total draws = 7 opening + (turn - 1) natural draws (on the play).
    draws = 7 + (by_turn - 1)

    success_count = 0

    if outcome_type in ("minimum_cards_seen", "has_tag"):
        tag = outcome_def["tag"]
        minimum = outcome_def.get("minimum", 1)

        for _ in range(iterations):
            rng.shuffle(deck)
            # Draw the top `draws` cards.
            drawn = deck[:draws]
            # Count how many have the target tag.
            count = sum(1 for _, tags in drawn if tag in tags)
            if count >= minimum:
                success_count += 1

    elif outcome_type == "all_groups_present":
        groups = outcome_def.get("groups", [])
        if not groups:
            # No groups means trivially satisfied.
            return MCResult(probability=1.0, iterations=iterations, successes=iterations)

        for _ in range(iterations):
            rng.shuffle(deck)
            drawn = deck[:draws]
            # Get all drawn tags in a flat set for fast membership.
            drawn_tags: set[str] = set()
            for _, tags in drawn:
                drawn_tags.update(tags)

            # Every group must have at least one drawn card with its tag.
            all_present = True
            for group in groups:
                group_tag = group["tag"]
                group_min = group.get("minimum", 1)
                count = sum(1 for _, tags in drawn if group_tag in tags)
                if count < group_min:
                    all_present = False
                    break

            if all_present:
                success_count += 1

    probability = success_count / iterations if iterations > 0 else 0.0
    return MCResult(
        probability=probability, iterations=iterations, successes=success_count
    )


def run_all_outcomes(
    deck_tags: dict[str, set[str]],
    outcome_defs: list[dict[str, Any]],
    iterations: int = 100_000,
    seed: int | None = 42,
) -> list[MCResult]:
    """Run Monte Carlo simulations for all outcome definitions.

    Args:
        deck_tags: Mapping of card_name -> set of tag strings.
        outcome_defs: List of outcome definition dicts.
        iterations: Number of trials per outcome.
        seed: Random seed (shared across outcomes for comparability).

    Returns:
        List of MCResult, one per outcome definition.
    """
    results: list[MCResult] = []
    for outcome_def in outcome_defs:
        result = run_simulation(deck_tags, outcome_def, iterations, seed)
        results.append(result)
    return results

# ---- Namespace setup ----

import sys as _sys

class _Module:
    pass

# Create the package hierarchy
_mtg = _Module()
_mtg.decklist = _Module()
_mtg.decklist.plain_text = _Module()
_mtg.decklist.parser = _Module()
_mtg.tags = _Module()
_mtg.tags.schema = _Module()
_mtg.tags.classifier = _Module()
_mtg.simulation = _Module()
_mtg.simulation.hypergeometric = _Module()
_mtg.simulation.outcome = _Module()
_mtg.simulation.monte_carlo = _Module()

# Register in sys.modules
_sys.modules["mtg_outcome_sim"] = _mtg
_sys.modules["mtg_outcome_sim.decklist"] = _mtg.decklist
_sys.modules["mtg_outcome_sim.decklist.plain_text"] = _mtg.decklist.plain_text
_sys.modules["mtg_outcome_sim.decklist.parser"] = _mtg.decklist.parser
_sys.modules["mtg_outcome_sim.tags"] = _mtg.tags
_sys.modules["mtg_outcome_sim.tags.schema"] = _mtg.tags.schema
_sys.modules["mtg_outcome_sim.tags.classifier"] = _mtg.tags.classifier
_sys.modules["mtg_outcome_sim.simulation"] = _mtg.simulation
_sys.modules["mtg_outcome_sim.simulation.hypergeometric"] = _mtg.simulation.hypergeometric
_sys.modules["mtg_outcome_sim.simulation.outcome"] = _mtg.simulation.outcome
_sys.modules["mtg_outcome_sim.simulation.monte_carlo"] = _mtg.simulation.monte_carlo

# Export public symbols to their module namespaces
_mtg.decklist.plain_text.parse_plain_text = parse_plain_text
_mtg.decklist.parser.ParsedCard = ParsedCard
_mtg.decklist.parser.ParsedDeck = ParsedDeck
_mtg.decklist.parser.parse_decklist = parse_decklist
_mtg.tags.schema.TagDefinition = TagDefinition
_mtg.tags.schema.CardTags = CardTags
_mtg.tags.schema.TagOverrides = TagOverrides
_mtg.tags.classifier.classify_card = classify_card
_mtg.tags.classifier.classify_cards = classify_cards
_mtg.simulation.hypergeometric.prob_at_least = prob_at_least
_mtg.simulation.hypergeometric.prob_exact = prob_exact
_mtg.simulation.hypergeometric.opening_hand_distribution = opening_hand_distribution
_mtg.simulation.hypergeometric.lands_by_turn = lands_by_turn
_mtg.simulation.outcome.OutcomeDefinition = OutcomeDefinition
_mtg.simulation.outcome.OutcomeConfig = OutcomeConfig
_mtg.simulation.outcome.load_outcomes = load_outcomes
_mtg.simulation.monte_carlo.MCResult = MCResult
_mtg.simulation.monte_carlo.run_simulation = run_simulation
_mtg.simulation.monte_carlo.run_all_outcomes = run_all_outcomes
